apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: ecommerce-prod
  labels:
    app: ecommerce-app
spec:
  type: ClusterIP
  selector:
    app: ecommerce-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
