apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecommerce-app-binding
  namespace: ecommerce-prod
subjects:
  - kind: ServiceAccount
    name: ecommerce-app
    namespace: ecommerce-prod
roleRef:
  kind: Role
  name: ecommerce-app-role
  apiGroup: rbac.authorization.k8s.io
